export const SPLASH_NAVIGATOR = 'SPLASH_NAVIGATOR';
export const AUTH_NAVIGATOR = 'AUTH_NAVIGATOR';
export const DASHBOARD_NAVIGATOR = 'DASHBOARD_NAVIGATOR';


export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
export const SIGN_IN_AS_SCREEN = 'SIGN_IN_AS_SCREEN'
export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const CREATE_ACCOUNT_SCREEN = 'CREATE_ACCOUNT_SCREEN';
export const OTP_SCREEN = 'OTP_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';